# Generated by Django 5.1 on 2024-09-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_role_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptinfo',
            name='type',
            field=models.SmallIntegerField(default=0, verbose_name='Department type'),
        ),
        migrations.AlterField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(blank=True, to='system.menu', verbose_name='菜单/权限'),
        ),
    ]
