# Generated by Django 4.1.8 on 2024-09-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_deptinfo_type_alter_role_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptinfo',
            old_name='is_active',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='is_active',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='is_active',
            new_name='status',
        ),
    ]
