# Generated by Django 4.1.8 on 2024-09-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_menu_name_alter_menu_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.menumeta', verbose_name='Menu meta'),
        ),
    ]
