# Generated by Django 5.1 on 2024-09-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='code',
            field=models.CharField(default=None, max_length=128, null=True, unique=True, verbose_name='权限标识'),
        ),
    ]
