# Generated by Django 5.1 on 2024-09-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_menu_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='rank',
        ),
        migrations.AddField(
            model_name='menumeta',
            name='rank',
            field=models.IntegerField(default=9999, verbose_name='菜单显示优先级'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=128, verbose_name='标识名称'),
        ),
    ]
