# Generated by Django 5.1 on 2024-10-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_remove_menu_rank_menumeta_rank_alter_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='redirect',
            field=models.CharField(blank=True, help_text='Redirect address', max_length=255, null=True, verbose_name='Redirect'),
        ),
    ]
