# Generated by Django 4.1.8 on 2024-09-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_supervisor',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
